export const POST_MOVIE = "POST_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const EDIT_MOVIE = "EDIT_MOVIE";
export const UPDATE_MOVIE = "UPDATE_MOVIE";

export const POST_MOVIE_SUCCESS = "POST_MOVIE_SUCCESS";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const EDIT_MOVIE_SUCCESS = "EDIT_MOVIE_SUCCESS";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
