export const GET_BOOKING_LIST_CHAIR = "GET_BOOKING_LIST_CHAIR";
export const CHOICE_CHAIR = "CHOICE_CHAIR ";
export const BOOKING_MOVIE_TICKET = "BOOKING_MOVIE_TICKET";

export const BOOKING_MOVIE_TICKET_SUCCESS = "BOOKING_MOVIE_TICKET_SUCCESS";
export const GET_BOOKING_LIST_CHAIR_SUCCESS = "GET_BOOKING_LIST_CHAIR_SUCCESS";
