export const POST_HISTORY_OF_USER_PROFILE = "POST_HISTORY_OF_USER_PROFILE";
export const CHANGE_PASSWORD_USER = "CHANGE_PASSWORD_USER";
export const POST_HISTORY_OF_USER_PROFILE_SUCCESS =
  "POST_HISTORY_OF_USER_PROFILE_SUCCESS";
