export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_MOVIE_DETAIL_SHOWTIMES_BY_MOVIECODE =
  "GET_MOVIE_DETAIL_SHOWTIMES_BY_MOVIECODE";

//---------ACTION - SAGA-----------//

export const GET_MOVIE_DETAIL_SHOWTIMES_BY_MOVIECODE_SUCCESS =
  "GET_MOVIE_DETAIL_SHOWTIMES_BY_MOVIECODE_SUCCESS";

export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
