export const GET_USER_LOGIN = "GET_USER_LOGIN";
export const GET_USER_LOGIN_SUCCESS = "GET_USER_LOGIN_SUCCESS";
export const ERR_MESSAGE = "ERR_MESSAGE";
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
